// Embeds the two HTML screens as strings so the deployed function does not need file access.
import { readFileSync, writeFileSync } from 'node:fs';
const pages = { index: 'public/index.html', appJs: 'public/app.js', appCss: 'public/app.css' };
const out = Object.entries(pages).map(([k, f]) => `export const ${k} = ${JSON.stringify(readFileSync(f, 'utf8'))};`).join('\n');
writeFileSync(new URL('../src/pages.ts', import.meta.url), `// Generated by scripts/build-pages.js. Do not edit.\n${out}\n`);
console.log('wrote src/pages.ts');
